@extends('layouts.master-front')

@section('content')
<section class="container-fluid aos-init aos-animate login-wrap1">
  <div class="content sec-pad justify">
    <div class="team-detail-wrap shape-wrap">
      <div class="container">
        <div class="membersingle-info team-detail-space">
          <div class="row align-items-start ">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 mrgn-b-2 mx-auto card py-5 px-4">
              <h1>Privacy Policy</h1>
              <div>
                <br>
                <h3>PRIVACY NOTICE</h3>
                <h6>Last updated September 09, 2020</h6>
                <p></p>
                <p><span style='font-size:15px;color:#595959;'>Thank you for choosing to be part of our community at&nbsp;Uplift K12 LLC, doing business as&nbsp;Uplift K12&nbsp;(&ldquo;<strong><span style=''>Uplift K12</span></strong>&rdquo;, &ldquo;<strong><span style=''>we</span></strong>&rdquo;, &ldquo;<strong><span style=''>us</span></strong>&rdquo;, or &ldquo;<strong><span style=''>our</span></strong>&rdquo;). We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about this privacy notice, or our practices with regards to your personal information, please contact us at&nbsp;teach@upliftk12.com.</span></p>
                <p><span style='font-size:15px;color:#595959;'>When you visit our website&nbsp;</span><a href="http://www.upliftk12.com/" target="_blank"><span style='font-size:15px;'>http://www.upliftk12.com</span></a><span style='font-size:15px;color:#595959;'>&nbsp;(the &quot;<strong><span style=''>Website</span></strong>&quot;),&nbsp;and more generally, use any of our services (the &quot;<strong><span style=''>Services</span></strong>&quot;, which include the&nbsp;Website), we appreciate that you are trusting us with your personal information. We take your privacy very seriously. In this privacy notice, we seek to explain to you in the clearest way possible what information we collect, how we use it and what rights you have in relation to it. We hope you take some time to read through it carefully, as it is important. If there are any terms in this privacy notice&nbsp;that you do not agree with, please discontinue use of our Services immediately.</span></p>
                <p><span style='font-size:15px;color:#595959;'>This privacy notice applies to all information collected through our Services (which, as described above, includes our&nbsp;Website</span><span style='font-size:15px;color:black;'>), as well as any related services, sales, marketing or events.</span></p>
                <p><strong><span style='font-size:15px;color:#595959;'>Please read this privacy notice&nbsp;carefully as it will help you understand what we do with the information that we collect.</span></strong></p>
                <p><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>TABLE OF CONTENTS</span></strong></p>
                <p style='font-size: 15px; '><a href="#infocollect"><span style='font-size:15px;'>1. WHAT INFORMATION DO WE COLLECT?</span></a></p>
                <p style='font-size: 15px; '><a href="#infouse"><span style='font-size:15px;'>2. HOW DO WE USE YOUR INFORMATION?</span></a></p>
                <p style='font-size: 15px; '><a href="#infoshare"><span style='font-size:15px;font-family:"Arial",sans-serif;'>3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?</span></a></p>
                <p style='font-size: 15px; '><a href="#whoshare"><span style='font-size:15px;font-family:"Arial",sans-serif;'>4. WHO WILL YOUR INFORMATION BE SHARED WITH?</span></a></p>
                <p style='font-size: 15px; '><a href="#cookies"><span style='font-size:15px;'>5. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</span></a></p>
                <p style='font-size: 15px; '><a href="#inforetain"><span style='font-size:15px;'>6. HOW LONG DO WE KEEP YOUR INFORMATION?</span></a></p>
                <p style='font-size: 15px; '><a href="#infosafe"><span style='font-size:15px;'>7. HOW DO WE KEEP YOUR INFORMATION SAFE?</span></a></p>
                <p style='font-size: 15px; '><a href="#privacyrights"><span style='font-size:15px;'>8. WHAT ARE YOUR PRIVACY RIGHTS?</span></a></p>
                <p style='font-size: 15px; '><a href="#DNT"><span style='font-size:15px;'>9. CONTROLS FOR DO-NOT-TRACK FEATURES</span></a></p>
                <p style='font-size: 15px; '><a href="#caresidents"><span style='font-size:15px;'>10. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</span></a></p>
                <p style='margin-right:0cm;margin-left:0cm;font-size:15px;'><a href="#policyupdates"><span style='font-size:15px;'>11. DO WE MAKE UPDATES TO THIS NOTICE?</span></a></p>
                <p style='margin-right:0cm;margin-left:0cm;font-size:15px;'><a href="#contact"><span style='font-size:15px;'>12. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</span></a></p>
                <p id="infocollect"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>1. WHAT INFORMATION DO WE COLLECT?</span></strong></p>
                <p><strong><span style='color:black;'><br> <strong><span style=''>Personal information you disclose to us</span></strong></span></strong></p>
                <p><em><strong><span style='font-size:15px;color:black;'>In Short: &nbsp;</span></strong></em><em><span style='font-size:15px;color:black;'>We collect information that you provide to us.</span></em></p>
                <p><span style='font-size:15px;color:black;'>We collect personal information that you voluntarily provide to us when you&nbsp;register on the&nbsp;Website,&nbsp;express an interest in obtaining information about us or our products and Services, when you participate in activities on the&nbsp;Website&nbsp;(such as by posting messages in our online forums or entering competitions, contests or giveaways)&nbsp;or otherwise when you contact us.</span></p>
                <p><span style='font-size:15px;color:black;'>The personal information that we collect depends on the context of your interactions with us and the&nbsp;Website, the choices you make and the products and features you use. The personal information we collect may include the following:</span></p>
                <p><strong><span style='font-size:15px;color:black;'>Personal Information Provided by You.</span></strong><span style='font-size:15px;color:black;'>&nbsp;We collect names; phone numbers; email addresses; mailing addresses; job titles; usernames; passwords; billing addresses; debit/credit card numbers; and other similar information.</span></p>
                <p><strong><span style='font-size:15px;color:black;'>Payment Data.&nbsp;</span></strong><span style='font-size:15px;color:black;'>We may collect data necessary to process your payment if you make purchases, such as your payment instrument number (such as a credit card number), and the security code associated with your payment instrument. All payment data is stored by</span><span style='font-size:15px;color:#595959;'>&nbsp;Paypal. You may find their privacy notice link(s) here:&nbsp;</span><a href="https://www.paypal.com/us/webapps/mpp/ua/privacy-full" target="_blank"><span style='font-size:15px;'>https://www.paypal.com/us/webapps/mpp/ua/privacy-full</span></a><span style='font-size:15px;color:#595959;'>.</span></p>
                <p><span style='font-size:18px;color:black;'>All personal information that you provide to us must be true, complete and accurate, and you must notify us of any changes to such personal information.</span></p>
                <p><strong><span style='color:black;'><br> <strong><span style=''>Information automatically collected</span></strong></span></strong></p>
                <p><strong><span style='font-size:18px;color:black;'>In Short: &nbsp;</span></strong><em><span style='font-size:18px;color:black;'>Some information &mdash; such as your Internet Protocol (IP) address and/or browser and device characteristics &mdash; is collected automatically when you visit our&nbsp;</span></em><em><span style='font-size:15px;color:black;'>Website</span></em><em><span style='font-size:18px;color:black;'>.</span></em></p>
                <p><span style='font-size:18px;color:black;'>&nbsp;</span></p>
                <p><span style='font-size:18px;color:black;'>We automatically collect certain information when you visit, use or navigate the&nbsp;</span><span style='font-size:15px;color:black;'>Website</span><span style='font-size:18px;color:black;'>. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about who and when you use our&nbsp;</span><span style='font-size:15px;color:black;'>Website</span><span style='font-size:18px;color:black;'>&nbsp;and other technical information. This information is primarily needed to maintain the security and operation of our&nbsp;</span><span style='font-size:15px;color:black;'>Website</span><span style='font-size:18px;color:black;'>, and for our internal analytics and reporting purposes.</span></p>
                <p><span style='font-size:18px;color:black;'>&nbsp;</span></p>
                <p><span style='font-size:18px;color:black;'>Like many businesses, we also collect information through cookies and similar technologies. &nbsp;</span></p>
                <p><span style='font-size:18px;color:black;'>&nbsp;</span></p>
                <p><span style='font-size:18px;color:black;'>The information we collect includes:</span></p>
                <ul style="margin-bottom:0cm;" type="square">
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><em><span style='font-size:15px;color:#595959;'>Log and Usage Data.</span></em><span style='font-size:15px;color:#595959;'>&nbsp;Log and usage data is service-related, diagnostic usage and performance information our servers automatically collect when you access or use our Website and which we record in log files. Depending on how you interact with us, this log data may include your IP address, device information, browser type and settings and information about your activity in the Website (such as the date/time stamps associated with your usage, pages and files viewed, searches and other actions you take such as which features you use), device event information (such as system activity, error reports (sometimes called &#39;crash dumps&#39;) and hardware settings).</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><em><span style='font-size:15px;color:#595959;'>Device Data.&nbsp;</span></em><span style='font-size:15px;color:#595959;'>We collect device data such as information about your computer, phone, tablet or other device you use to access the&nbsp;</span><span style='font-size:15px;'>Website</span><span style='font-size:15px;color:#595959;'>. Depending on the device used, this device data may include information such as your IP address (or proxy server), device application identification numbers, location, browser type, hardware model Internet service provider and/or mobile carrier, operating system configuration&nbsp;information.</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><em><span style='font-size:15px;color:#595959;'>Location Data.</span></em><span style='font-size:15px;color:#595959;'>&nbsp;We collect information data such as information about your device&#39;s location, which can be either precise or imprecise. How much information we collect depends on the type of settings of the device you use to access the Website. For example, we may use GPS and other technologies to collect geolocation data that tells us your current location (based on your IP address). You can opt out of allowing us to collect this information either by refusing access to the information or by disabling your Locations settings on your device. Note however, if you choose to opt out, you may not be able to use certain aspects of the Services.</span></li>
                </ul>
                <p id="infouse"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>2. HOW DO WE USE YOUR INFORMATION?</span></strong></p>
                <p><strong><span style='font-size:15px;color:black;'>In Short: &nbsp;</span></strong><em><span style='font-size:15px;color:black;'>We process your information for purposes based on legitimate business interests, the fulfillment of our contract with you, compliance with our legal obligations, and/or your consent.</span></em></p>
                <p><span style='font-size:15px;color:black;'>We use personal information collected via our&nbsp;Website&nbsp;for a variety of business purposes described below. We process your personal information for these purposes in reliance on our legitimate business interests, in order to enter into or perform a contract with you, with your consent, and/or for compliance with our legal obligations. We indicate the specific processing grounds we rely on next to each purpose listed below.</span></p>
                <p><span style='font-size:15px;color:black;'>We use the information we collect or receive:</span></p>
                <ul style="margin-bottom:0cm;" type="square">
                  <li style='margin:0cm;margin-bottom:     13.5pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To facilitate account creation and logon process.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;If you choose to link your account with us to a third-party account (such as your Google or Facebook account), we use the information you allowed us to collect from those third parties to facilitate account creation and logon process for the performance of the contract.</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To post testimonials.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We post testimonials on our Website that may contain personal information. Prior to posting a testimonial, we will obtain your consent to use your name and the consent of the testimonial. If you wish to update, or delete your testimonial, please contact us at teach@upliftk12.com and be sure to include your name, testimonial location, and contact information.</span><span style='font-size:18px;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Request feedback.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may use your information to request feedback and to contact you about your use of our Website.</span><span style='font-size:18px;'><br>&nbsp;</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To enable user-to-user communications.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may use your information in order to enable user-to-user communications with each user&#39;s consent.</span><span style='font-size:18px;'><br>&nbsp;</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To manage user accounts</span></strong><span style='font-size:15px;color:#595959;'>. We may use your information for the purposes of managing our account and keeping it in working order.</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To send administrative information to you.&nbsp;</span></strong><span style='font-size:15px;color:#595959;'>We may use your personal information to send you product, service and new feature information and/or information about changes to our terms, conditions, and policies.</span><span style='font-size:18px;font-family:     "Arial",sans-serif;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To protect our Services.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may use your information as part of our efforts to keep our Website safe and secure (for example, for fraud monitoring and prevention).</span><span style='font-size:18px;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To enforce our terms, conditions and policies for business purposes, to comply with legal and regulatory requirements or in connection with our contract.</span></strong><span style='font-size:18px;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To respond to legal requests and prevent harm.&nbsp;</span></strong><span style='font-size:15px;color:#595959;'>If we receive a subpoena or other legal request, we may need to inspect the data we hold to determine how to respond.</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Fulfill and manage your orders.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may use your information to fulfill and manage your orders, payments, returns, and exchanges made through the Website.</span><span style='font-size:18px;'><br><br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Administer prize draws and competitions.&nbsp;</span></strong><span style='font-size:15px;color:#595959;'>We may use your information to administer prize draws and competitions when you elect to participate in our competitions.</span><span style='font-size:18px;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To deliver and facilitate delivery of services to the user.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may use your information to provide you with the requested service.</span><span style='font-size:18px;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To respond to user inquiries/offer support to users.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may use your information to respond to your inquiries and solve any potential issues you might have with the use of our Services.</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>To send you marketing and promotional communications.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We and/or our third-party marketing partners may use the personal information you send to us for our marketing purposes, if this is in accordance with your marketing preferences. For example, when expressing an interest in obtaining information about us or our Website, subscribing to marketing or otherwise contacting us, we will collect personal information from you. You can opt-out of our marketing emails at any time (see the &quot;</span><span style="color:windowtext;"><a href="#privacyrights"><span style='font-size:15px;color:#595959;'>WHAT ARE YOUR PRIVACY RIGHTS</span></a></span><span style='font-size:15px;color:#595959;'>&quot; below).</span><span style='font-size:18px;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Deliver targeted advertising to you.&nbsp;</span></strong><span style='font-size:15px;color:#595959;'>We may use your information to develop and display personalized content and advertising (and work with third parties who do so) tailored to your interests and/or location and to measure its effectiveness.</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>For other business purposes.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may use your information for other business purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Website, products, marketing and your experience. We may use and store this information in aggregated and anonymized form so that it is not associated with individual end users and does not include personal information. We will not use identifiable personal information without your consent.</span></li>
                </ul>
                <p id="infoshare"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?</span></strong></p>
                <p><em><strong><span style='font-size:15px;color:#595959;'>In Short:&nbsp;</span></strong></em><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><em><span style='font-size:15px;color:#595959;'>We only share information with your consent, to comply with laws, to provide you with services, to protect your rights, or to fulfill business obligations.</span></em></p>
                <p><span style='font-size:15px;color:#595959;'>We may process or share your data that we hold based on the following legal basis:</span></p>
                <ul style="margin-bottom:0cm;" type="square">
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Consent:</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may process your data if you have given us specific consent to use your personal information in a specific purpose.</span><span style='font-size:18px;'>&nbsp;<br>&nbsp;</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Legitimate Interests:</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may process your data when it is reasonably necessary to achieve our legitimate business interests.</span><span style='font-size:18px;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Performance of a Contract:&nbsp;</span></strong><span style='font-size:15px;color:#595959;'>Where we have entered into a contract with you, we may process your personal information to fulfill the terms of our contract.</span><span style='font-size:18px;font-family:     "Arial",sans-serif;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Legal Obligations:</span></strong><span style='font-size:15px;font-family:     "Arial",sans-serif;color:#595959;'>&nbsp;We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal process, such as in response to a court order or a subpoena (including in response to public authorities to meet national security or law enforcement requirements).</span><span style='font-size:18px;font-family:     "Arial",sans-serif;'><br> <br></span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Vital Interests:</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud, situations involving potential threats to the safety of any person and illegal activities, or as evidence in litigation in which we are involved.</span></li>
                </ul>
                <p><span style='font-size:15px;color:#595959;'>More specifically, we may need to process your data or share your personal information in the following situations:</span></p>
                <ul style="margin-bottom:0cm;" type="square">
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Business Transfers.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</span></li>
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Vendors, Consultants and Other Third-Party Service Providers.</span></strong><span style='font-size:15px;color:#595959;'>&nbsp;We may share your data with third-party vendors, service providers, contractors or agents who perform services for us or on our behalf and require access to such information to do that work. Examples include: payment processing, data analysis, email delivery, hosting services, customer service and marketing efforts. We may allow selected third parties to use tracking technology on the Website, which will enable them to collect data on our behalf about how you interact with our Website over time. This information may be used to, among other things, analyze and track data, determine the popularity of certain content, pages or features, and better understand online activity. Unless described in this notice, we do not share, sell, rent or trade any of your information with third parties for their promotional purposes.</span></li>
                </ul>
                <p id="whoshare"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>4. WHO WILL YOUR INFORMATION BE SHARED WITH?</span></strong></p>
                <p><em><strong><span style='font-size:15px;color:#595959;'>In Short:</span></strong></em><em><strong><span style='font-size:18px;color:#595959;'>&nbsp;</span></strong></em><strong><span style='font-size:18px;color:#595959;'>&nbsp;</span></strong><em><span style='font-size:15px;color:#595959;'>We only share information with the following third parties.</span></em></p>
                <p><span style='font-size:15px;color:#595959;'>&nbsp;</span><span style='font-size:18px;color:#595959;'>&nbsp;</span></p>
                <p><span style='font-size:15px;color:#595959;'>We only share and disclose your information with the following third parties. We have categorized each party so that you may easily understand the purpose of our data collection and processing practices. If we have processed your data based on your consent and you wish to revoke your consent, please contact us using the contact details provided in the section below titled &quot;</span><a href="#contact"><span style='font-size:18px;color:#595959;'>HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</span></a><span style='font-size:15px;color:#595959;'>&quot;.</span></p>
                <ul style="margin-bottom:0cm;" type="square">
                  <li style='margin:0cm;margin-bottom:.0001pt;font-size:15px;color:black;'><strong><span style='font-size:15px;color:#595959;'>Web and Mobile Analytics</span></strong><span style='font-size:18px;'><br>&nbsp;</span><span style='font-size:15px;color:#595959;'>Google Analytics</span></li>
                </ul>
                <p id="cookies"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>5. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</span></strong></p>
                <p><em><strong><span style='font-size:15px;color:#595959;'>In Short:&nbsp;</span></strong></em><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><em><span style='font-size:15px;color:#595959;'>We may use cookies and other tracking technologies to collect and store your information.</span></em></p>
                <p><span style='font-size:15px;color:#595959;'>We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Notice.</span></p>
                <p id="inforetain"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>6. HOW LONG DO WE KEEP YOUR INFORMATION?</span></strong></p>
                <p><em><strong><span style='font-size:15px;color:#595959;'>In Short:&nbsp;</span></strong></em><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><em><span style='font-size:15px;color:#595959;'>We keep your information for as long as necessary to fulfill the purposes outlined in this privacy notice&nbsp;unless otherwise required by law.</span></em></p>
                <p><span style='font-size:15px;color:#595959;'>We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting or other legal requirements). No purpose in this notice will require us keeping your personal information for longer than&nbsp;</span><span style='font-size:15px;color:black;'>the period of time in which users have an account with us</span><span style='font-size:15px;color:#595959;'>.</span></p>
                <p><span style='font-size:15px;color:#595959;'>When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</span></p>
                <p id="infosafe"><span style='font-size:18px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>7. HOW DO WE KEEP YOUR INFORMATION SAFE?</span></strong></p>
                <p><em><strong><span style='font-size:15px;color:#595959;'>In Short:&nbsp;</span></strong></em><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><em><span style='font-size:15px;color:#595959;'>We aim to protect your personal information through a system of organizational and technical security measures.</span></em></p>
                <p><span style='font-size:15px;color:#595959;'>We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security, and improperly collect, access, steal, or modify your information. Although we will do our best to protect your personal information, transmission of personal information to and from our&nbsp;Website&nbsp;is at your own risk. You should only access the&nbsp;Website&nbsp;within a secure environment.</span></p>
                <p id="privacyrights"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>8. WHAT ARE YOUR PRIVACY RIGHTS?</span></strong></p>
                <p><em><strong><span style='font-size:15px;color:#595959;'>In Short:&nbsp;</span></strong></em><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><em><span style='font-size:15px;color:#595959;'>You may review, change, or terminate your account at any time.</span></em></p>
                <p><span style='font-size:15px;color:#595959;'>If you are resident in the European Economic Area and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here:&nbsp;</span><a href="http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm" target="_blank"><span style='font-size:15px;'>http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm</span></a><span style='font-size:15px;color:#3030F1;'>.</span></p>
                <p><span style='font-size:15px;color:#595959;'>If you are resident in Switzerland, the contact details for the data protection authorities are available here:&nbsp;</span><a href="https://www.edoeb.admin.ch/edoeb/en/home.html" target="_blank"><span style='font-size:15px;'>https://www.edoeb.admin.ch/edoeb/en/home.html</span></a><span style='font-size:15px;color:#3030F1;'>.</span></p>
                <p><span style='font-size:15px;color:#595959;'>If you have questions or comments about your privacy rights, you may email us at&nbsp;teach@upliftk12.com.</span></p>
                <p><span style='font-size:18px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='color:black;'>Account Information</span></strong></p>
                <p><span style='font-size:15px;color:#595959;'>If you would at any time like to review or change the information in your account or terminate your account, you can:</span></p>
                <p><span style='font-size:15px;color:black;'>&nbsp; &nbsp; ■ &nbsp;</span><span style='font-size:15px;color:#595959;'>Contact us using the contact information provided.</span></p>
                <p><span style='font-size:15px;color:#595959;'>Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, we may retain some information in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our Terms of Use and/or comply with applicable legal requirements.</span></p>
                <p><strong><u><span style='font-size:15px;color:#595959;'>Cookies and similar technologies:</span></u></strong><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><span style='font-size:15px;color:#595959;'>Most Web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our&nbsp;Website. To opt-out of interest-based advertising by advertisers on our&nbsp;Website&nbsp;visit</span><span style='font-size:15px;color:black;'>&nbsp;</span><a href="http://www.aboutads.info/choices/" target="_blank"><span style='font-size:15px;'>http://www.aboutads.info/choices/</span></a><span style='font-size:15px;color:#595959;'>.</span></p>
                <p><strong><u><span style='font-size:15px;color:#595959;'>Opting out of email marketing:</span></u></strong><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><span style='font-size:15px;color:#595959;'>You can unsubscribe from our marketing email list at any time by clicking on the unsubscribe link in the emails that we send or by contacting us using the details provided below. You will then be removed from the marketing email list &ndash; however, we may still communicate with you, for example to send you service-related emails that are necessary for the administration and use of your account, to respond to service requests, or for other non-marketing purposes. To otherwise opt-out, you may:</span></p>
                <p><span style='font-size:15px;color:black;'>&nbsp; &nbsp; ■&nbsp;</span><span style='font-size:15px;color:#595959;'>&nbsp;Contact us using the contact information provided.</span></p>
                <p id="DNT"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>9. CONTROLS FOR DO-NOT-TRACK FEATURES</span></strong></p>
                <p><span style='font-size:15px;color:#595959;'>Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (&ldquo;DNT&rdquo;) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage, no uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.</span></p>
                <p id="caresidents"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>10. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</span></strong></p>
                <p><em><strong><span style='font-size:15px;color:#595959;'>In Short:&nbsp;</span></strong></em><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><em><span style='font-size:15px;color:#595959;'>Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.</span></em></p>
                <p><span style='font-size:15px;color:#595959;'>California Civil Code Section 1798.83, also known as the &ldquo;Shine The Light&rdquo; law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.</span></p>
                <p><span style='font-size:15px;color:#595959;'>If you are under 18 years of age, reside in California, and have a registered account with the Website, you have the right to request removal of unwanted data that you publicly post on the Website. To request removal of such data, please contact us using the contact information provided below, and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Website, but please be aware that the data may not be completely or comprehensively removed from all our systems (e.g. backups, etc.). &nbsp;</span></p>
                <p id="policyupdates"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>11. DO WE MAKE UPDATES TO THIS NOTICE?</span></strong></p>
                <p><em><strong><span style='font-size:15px;color:#595959;'>In Short:&nbsp;</span></strong></em><strong><span style='font-size:15px;color:#595959;'>&nbsp;</span></strong><em><span style='font-size:15px;color:#595959;'>Yes, we will update this notice as necessary to stay compliant with relevant laws.</span></em></p>
                <p><span style='font-size:15px;color:#595959;'>We may update this privacy notice&nbsp;from time to time. The updated version will be indicated by an updated &ldquo;Revised&rdquo; date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice&nbsp;frequently to be informed of how we are protecting your information.</span></p>
                <p id="contact"><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:19px;color:black;'>12. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</span></strong></p>
                <p><span style='font-size:15px;color:#595959;'>If you have questions or comments about this notice, you may&nbsp;email us at&nbsp;teach@upliftk12.com&nbsp;or by post to:</span></p>
                <p><span style='font-size:15px;color:#595959;'>Uplift K12 LLC</span><span style='font-size:18px;color:#595959;'>&nbsp;</span></p>
                <p><span style='font-size:15px;color:#595959;'>Houston,&nbsp;TX&nbsp;77090</span></p>
                <p><span style='font-size:15px;color:#595959;'>United States</span></p>
                <p><span style='font-size:15px;color:black;'>&nbsp;</span></p>
                <p><strong><span style='font-size:15px;color:black;'>HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</span></strong></p>
                <p><span style='font-size:18px;color:black;'>Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please&nbsp;visit:&nbsp;teach@upliftk12.com. We will respond to your request within 30 days.</span></p>
                <p style='margin-right:5.75pt;margin-left:5.0pt;font-size:15px;margin:0cm;margin-bottom:.0001pt;margin-top:8.1pt;text-align:justify;line-height:113%;'>&nbsp;</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection
@push('styles')
<style type="text/css">
  .login-wrap {
    background-image: url(public/images/background-login.jpg);
    background-position: center center;
    background-size: cover;
    background-repeat: no-repeat;
    position: relative;
  }
  .login-wrap::after {
    position: absolute;
    width: 100%;
    height: 100%;
    background-color: rgba(0,0,0,0.4);
    display: block;
    content: "";
    top: 0;
    left: 0;
    z-index: 1;
  }
  .justify {
    position: relative;
    z-index: 2;
  }
  .btn-submit {
    font-family: "Poppins", sans-serif;
    font-weight: 500;
    font-size: 16px;
    letter-spacing: 1px;
    display: inline-block;
    padding: 10px 15px;
    border-radius: 5px;
    transition: 0.5s;
    color: #fff;
    background: #6f48a9;
    position: relative;
  }
</style>
@endpush